index:
    path: /registrate
    controller: App\Controller\UserController::index
    methods: GET

login:
    path: /login
    controller: App\Controller\UserController::loginUserForm
    methods: GET

login_user:
    path: /user/login
    controller: App\Controller\UserController::loginUser
    methods: POST

mainPage:
    path: /
    controller: App\Controller\StorefrontController::mainPage

add_order:
    path: /order/create
    controller: App\Controller\StorefrontController::createOrder
    methods: POST

add_user:
    path: /user/register
    controller: App\Controller\UserController::registerUser
    methods: POST

logout:
    path: /logout
    controller: App\Controller\UserController::logoutUser

error:
    path: /error
    controller: App\Controller\UserController::error

show_user:
    path: /user/
    controller: App\Controller\UserController::showUser
    methods: POST

delete_user:
    path: /user/delete
    controller: App\Controller\UserController::deleteUser
    methods: POST

update_user:
    path: /user/update
    controller: App\Controller\UserController::updateUser
    methods: POST

found_user:
    path: /user/find
    controller: App\Controller\UserController::showUser
    methods: POST



