<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHm6YWkH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHm6YWkH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHm6YWkH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHm6YWkH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHm6YWkH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hm6YWkH',
    'container.build_id' => '1b220b5f',
    'container.build_time' => 1719038326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHm6YWkH');
